<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "BLUDIT",
    "slogan": "欢迎使用Bludit",
    "description": "Congratulations you have successfully installed your**Bludit**",
    "footer": "Copyright © 2025",
    "itemsPerPage": 6,
    "theme": "alternative",
    "adminTheme": "tabler",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/103.181.135.149",
    "emailFrom": "no-reply@103.181.135.149",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}