<!doctype html>
<html lang="<?php echo Theme::lang() ?>">
<head>
	<meta charset="<?php echo CHARSET ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
	<meta http-equiv="X-UA-Compatible" content="ie=edge"/>
	<meta name="robots" content="noindex,nofollow">
	<meta name="generator" content="Bludit">
	<title><?php echo $layout['title'] ?></title>

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo HTML_PATH_CORE_IMG.'favicon.png?version='.BLUDIT_VERSION ?>">

	<!-- CSS files -->
	<?php
		echo Theme::cssTabler();
		echo Theme::cssTablerVendors();
		echo Theme::cssBootstrapIcons(); // 保留 Bootstrap Icons
		echo Theme::css(array(
			'jquery.datetimepicker.min.css',
			'select2.min.css',
			'select2-bootstrap-5-theme.min.css'
		), DOMAIN_CORE_CSS);
	?>

	<!-- Javascript -->
	<?php
		echo Theme::jquery();
		// Tabler 已包含 Bootstrap 5,但我们保留 jQuery 兼容性
		echo Theme::jsTabler();
		echo Theme::jsSortable();
		echo Theme::js(array(
			'jquery.datetimepicker.full.min.js',
			'select2.full.min.js',
			'functions.js'
		), DOMAIN_CORE_JS, null);
	?>

	<!-- Plugins -->
	<?php Theme::plugins('adminHead') ?>
</head>
<body>

<!-- Plugins -->
<?php Theme::plugins('adminBodyBegin') ?>

<!-- Javascript dynamic generated by PHP -->
<?php
	echo '<script charset="utf-8">'.PHP_EOL;
	include(PATH_CORE_JS.'variables.php');
	echo '</script>'.PHP_EOL;

	echo '<script charset="utf-8">'.PHP_EOL;
	include(PATH_CORE_JS.'bludit-ajax.php');
	echo '</script>'.PHP_EOL;
?>

<!-- Overlay background -->
<div id="jsshadow"></div>

<!-- Alert -->
<?php include('html/alert.php'); ?>

<div class="page">
	<!-- Sidebar -->
	<?php include('html/sidebar.php'); ?>
	
	<!-- Navbar for mobile -->
	<?php include('html/navbar.php'); ?>
	
	<div class="page-wrapper">
		<!-- Page header -->
		<div class="page-header d-print-none">
			<div class="container-xl">
				<div class="row g-2 align-items-center">
					<div class="col">
						<?php 
							if (isset($layout['icon']) && isset($layout['title'])) {
								echo Bootstrap::pageTitle(array(
									'icon' => $layout['icon'],
									'title' => $layout['title']
								));
							}
						?>
					</div>
				</div>
			</div>
		</div>
		
		<!-- Page body -->
		<div class="page-body">
			<div class="container-xl">
				<?php
					if (Sanitize::pathFile(PATH_ADMIN_VIEWS, $layout['view'].'.php')) {
						include(PATH_ADMIN_VIEWS.$layout['view'].'.php');
					} elseif ($layout['plugin'] && method_exists($layout['plugin'], 'adminView')) {
						echo $layout['plugin']->adminView();
					} else {
						echo '<h1 class="text-center">'.$L->g('Page not found').'</h1>';
						echo '<h2 class="text-center">'.$L->g('Choose a page from the sidebar.').'</h2>';
					}
				?>
			</div>
		</div>
		
		<!-- Footer -->
		<footer class="footer footer-transparent d-print-none">
			<div class="container-xl">
				<div class="row text-center align-items-center">
					<div class="col-12 col-lg-auto mt-3 mt-lg-0">
						<ul class="list-inline list-inline-dots mb-0">
							<li class="list-inline-item">
								<?php echo (defined('BLUDIT_PRO')) ? 'BLUDIT PRO' : 'BLUDIT' ?>
							</li>
							<li class="list-inline-item">
								Version <?php echo BLUDIT_VERSION ?>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
	</div>
</div>

<!-- Custom Tabler JS -->

<!-- Plugins -->
<?php Theme::plugins('adminBodyEnd') ?>

</body>
</html>
