<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "BLUDIT",
    "slogan": "Welcome to Bludit",
    "description": "Multi-site CMS powered by Bludit",
    "footer": "Copyright © 2025",
    "itemsPerPage": 6,
    "theme": "alternative",
    "adminTheme": "tabler",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "",
    "emailFrom": "",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "markdownParser": true
}
